# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'root.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(840, 556)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 3, 1, 1)
        self.portEdit = QtWidgets.QLineEdit(Form)
        self.portEdit.setObjectName("portEdit")
        self.gridLayout.addWidget(self.portEdit, 0, 4, 1, 1)
        self.ipEdit = QtWidgets.QLineEdit(Form)
        self.ipEdit.setObjectName("ipEdit")
        self.gridLayout.addWidget(self.ipEdit, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 1, 3, 1, 2)
        self.openButton = QtWidgets.QPushButton(Form)
        self.openButton.setObjectName("openButton")
        self.gridLayout.addWidget(self.openButton, 1, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 5, 1, 1)
        self.accessLable = QtWidgets.QLabel(Form)
        self.accessLable.setObjectName("accessLable")
        self.gridLayout.addWidget(self.accessLable, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.stateLable = QtWidgets.QLabel(Form)
        self.stateLable.setObjectName("stateLable")
        self.gridLayout.addWidget(self.stateLable, 0, 5, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "端口"))
        self.label.setText(_translate("Form", "内网地址"))
        self.pushButton_2.setText(_translate("Form", "PushButton"))
        self.openButton.setText(_translate("Form", "开启"))
        self.accessLable.setText(_translate("Form", "TextLabel"))
        self.label_4.setText(_translate("Form", "接入"))
        self.stateLable.setText(_translate("Form", "未在运行"))
